### ISSUE TITLE
Sending no user agent results in a 403 error from avatar.com

### ISSUE THREAD

**Issue by jonphipps** [seejohnrun/gravatar_helper#1]
If no 'user_agent' has been configured in php.ini a 403 error is returned from the request generated by the 'profile_from_hash' method (the tests are failing for me).  Adding this line at the beginning of the method seems to fix it:

```
ini_set('user_agent', "PHPunitUserAgent1.0");   <---

public static function profile_from_hash($hash)
{
    if (!ini_get('user_agent'))
    {
        ini_set('user_agent', "PHPunitUserAgent1.0");
    }
    if ($raw = file_get_contents(self::$profile_base_url . $hash . '.json'))
    ...
```

Apparently any old user_agent will do.

Sorry about the lack of pull request, but hopefully this is easy enough without it.

**Comment by seejohnrun** [comment]
I like this better than an ini_set - thoughts?

**Comment by jonphipps** [comment]
Much better!

On Tuesday, December 4, 2012, John Crepezzi wrote:

> I like this better than an ini_set - thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/seejohnrun/gravatar_helper/issues/1#issuecomment-11029705.

## 

Jon
